CREATE DATABASE dbShoeInventory;

USE dbShoeInventory;

CREATE TABLE tblSize(
SID int AUTO_INCREMENT NOT NULL,
Size float NOT NULL,
PRIMARY KEY(SID)
);

ALTER TABLE tblSize AUTO_INCREMENT = 1001;

CREATE TABLE tblBrand(
BID int AUTO_INCREMENT NOT NULL,
Brand VARCHAR(20) NOT NULL,
PRIMARY KEY(BID)
);

ALTER TABLE tblBrand AUTO_INCREMENT = 5001;

CREATE TABLE tblColor(
CID int AUTO_INCREMENT NOT NULL,
Color VARCHAR(20) NOT NULL,
PRIMARY KEY(CID)
);

ALTER TABLE tblColor AUTO_INCREMENT = 6001;

CREATE TABLE tblType(
TID int AUTO_INCREMENT NOT NULL,
Type VARCHAR(20) NOT NULL,
PRIMARY KEY(TID)
);

ALTER TABLE tblType AUTO_INCREMENT = 7001;

CREATE TABLE tblCategory(
CatID int AUTO_INCREMENT NOT NULL,
Category VARCHAR(10),
PRIMARY KEY(CatID)
);

ALTER TABLE tblCategory AUTO_INCREMENT = 8001;

CREATE TABLE tblShoe(
ShoeID int AUTO_INCREMENT NOT NULL,
BID int NOT NULL,
SID int NOT NULL,
CID int NOT NULL,
TID int NOT NULL,
CatID int NOT NULL,
Price double NOT NULL,
PRIMARY Key(ShoeID)
);

ALTER TABLE tblShoe AUTO_INCREMENT = 10001;

CREATE TABLE tblInventory(
IID int AUTO_INCREMENT NOT NULL,
ShoeID int NOT NULL,
Received_Qty int NOT NULL,
Date_received Date NOT NULL,
Receiver_ID int NOT NULL,
PRIMARY KEY(IID)
);

ALTER TABLE tblInventory AUTO_INCREMENT = 9001;

CREATE TABLE tblUser(
UID int AUTO_INCREMENT NOT NULL,
FName VARCHAR(30) NOT NULL,
MName VARCHAR(30) NOT NULL,
LName VARCHAR(30) NOT NULL,
Gender char NOT NULL,
BDate Date NOT NULL,
User VARCHAR(20) NOT NULL,
Pass VARCHAR(50) NOT NULL,
Type int NOT NULL,
PRIMARY KEY(UID)
);

ALTER TABLE tblUser AUTO_INCREMENT = 100;

CREATE TABLE tblLog(
LogID int AUTO_INCREMENT NOT NULL,
UID int NOT NULL,
employee_name VARCHAR(100) NOT NULL,
timeIn Time(0) NOT NULL,
Login_date Date NOT NULL,
timeOut Time(0),
Logout_date Date,
PRIMARY Key(LogID)
);

ALTER TABLE tblLog AUTO_INCREMENT = 2001;

CREATE TABLE tblOrder(
orderID int AUTO_INCREMENT NOT NULL,
orderNumber int NOT NULL,
oShoeID int NOT NULL,
oQTY int NOT NULL,
oDATE Date NOT NULL,
PRIMARY KEY(orderID)
);



INSERT INTO tblSize(Size) VALUES
(4),(4.5),(5),(5.5),(6),(6.5),(7),(7.5),(8),(8.5),(9),(9.5),(10),(10.5),(11),(11.5),(12);

INSERT INTO tblBrand(Brand) VALUES
('VANS'),('WBROWN'),('FILA'),('NIKE');

INSERT INTO tblColor(Color) VALUES
('RED'),('BLUE'),('BLACK'),('BROWN'),('WHITE'),('GREEN');

INSERT INTO tblType(Type) VALUES
('RUBBER'),('LEATHER');

INSERT INTO tblCategory(Category) VALUES
('MALE'),('FEMALE'),('UNISEX');


SELECT * FROM tblInventory;
SELECT * FROM tblShoe;
SELECT * FROM tblCategory;
SELECT * FROM tblType;
SELECT * FROM tblColor;
SELECT * FROM tblBrand;
SELECT * FROM tblSize;
SELECT * FROM tblUser;
SELECT * FROM tblOrder;
